server:
  port: 8085

spring:
  application:
    name: QUESTION-GENERATOR-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/question-service-db

gemini:
  api:
    key: AIzaSyCGY1Apt7UEUPhGc0lL2Pxl7caGpKPe3Jc
    url: https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent

    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka